[book]
authors = ["acehinnnqru"]
language = "en"
multilingual = false
src = "src"
title = "@acehinnnqru's"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
