baseURL = 'https://me.acehinnnqru.com/'
languageCode = 'en-us'
title = '@acehinnnqru'
theme = 'nostyle'

[author]
    name = 'acehinnnqru'
    email = 'acehinnnqru@gmail.com'

[module]
[[module.mounts]]
    source = 'content'
    target = 'content'
    excludeFiles = ['**/README.md']

