baseURL = 'https://me.acehinnnqru.com/'
languageCode = 'en-us'
title = '@acehinnnqru'
theme = 'nostyle'

azureAppInsightsKey = '3815820d-7e91-4ed5-9b85-9424562b875e'

[author]
    name = 'acehinnnqru'
    email = 'acehinnnqru@gmail.com'

[frontmatter]
    date = [ ':default', ':fileModTime']

[module]
[[module.mounts]]
    source = 'content'
    target = 'content'
    excludeFiles = ['**/README.md']

